# Generated by Django 6.0.2 on 2026-02-05 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_employees_project_employees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='employees',
            field=models.ManyToManyField(to='api.employees'),
        ),
    ]
