# Generated by ChatGPT on 2026-02-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_project_employees"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employees",
            name="first_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="employees",
            name="last_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="employees",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
