# Generated by Django 6.0.2 on 2026-03-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_employees_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='security_level',
            field=models.CharField(choices=[('Public', 'Public'), ('Internal', 'Internal'), ('Confidential', 'Confidential'), ('Restricted', 'Restricted')], default='Internal', max_length=20),
        ),
    ]
