# Generated by Django 6.0.2 on 2026-03-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_project_comments_null_to_empty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='comments',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
