# Generated by Django 6.0.2 on 2026-03-12 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_project_comments_not_null'),
        ('api', '0014_alter_project_comments'),
    ]

    operations = [
    ]
